// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhqtguedferjiintpzbc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpocXRndWVkZmVyamlpbnRwemJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NjAyNDYsImV4cCI6MjA3MDIzNjI0Nn0.OMtrYRK9UGQTzlb6dS5t-pfS3ytFtRBWtr40XSN3IQA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});